### ISSUE TITLE
Extension Activation Failure due to Different Path in VSCodium

### ISSUE THREAD

**Issue by anxkhn** [Suyash-Purwar/hackerrank-vscode#2]
**Issue Description:**

When attempting to activate the `undefined_publisher.hackerrank-vscode` extension in VSCodium, the activation fails with the following error:

```
Activating extension •undefined_publisher.hackerrank-vscode' failed: Cannot find module
•c:\Users\Administrator\Desktop\hackerrank-vscode\out\extension.js' Require stack:
- c:\Program Files\VSCodium\resources\app\out\vs\loader.js
- c:\Program Files\VSCodium\resources\app\out\bootstrap-amd.js
- c:\Program Files\VSCodium\resources\app\out\bootstrap-fork.js
- .
```

**Root Cause:**

The issue appears to be related to a path change in VSCodium as opposed to Visual Studio Code (VSCode). The extension is looking for a module at the path `c:\Users\Administrator\Desktop\hackerrank-vscode\out\extension.js`, but this path structure may not be valid in VSCodium.

**Steps to Reproduce:**

1. Install VSCodium.
2. Install the `undefined_publisher.hackerrank-vscode` extension.
3. Attempt to activate the extension.

**Expected Behavior:**

The extension should activate successfully without any errors.

**Actual Behavior:**

The extension activation fails with the mentioned error due to the path discrepancy.
![image](https://github.com/Suyash-Purwar/hackerrank-vscode/assets/83116240/950768a5-d3ff-49bf-93bc-f58b2ef6794c)

**Environment:**

- Operating System: Independent/ Windows
- VSCodium Version: [1.84.2.23314.msi](https://github.com/VSCodium/vscodium/releases/download/1.84.2.23314/VSCodium-x64-1.84.2.23314.msi)

**Additional Information:**

Any additional information that might be relevant to resolving the issue.

**Possible Solutions:**

- Modify the extension settings or code to accommodate the path changes in VSCodium.

**Comment by suyash-purwar** [comment]
Thanks @anxkhn for pointing this out. You documented the issue very nicely. I missed one step in the installation section of the guide. 

Run `npm install` and then press `F5`. Let me know if the error toast still persists.

It should fix this problem but I've encountered one more issue related to the EJS template path. I'm working on it. #3

**Comment by suyash-purwar** [comment]
Closing this issue for now.
